### ISSUE TITLE
Windows Media Source Filter - DirectShow

### ISSUE THREAD

**Issue by mrpenguinb** [ValeryAnisimovsky/GameMediaFormatsCoreFilters#2]
Just making this and "issue" since there are some games that use the Windows Media Source Filter codec/filter (still not sure what to call it, could you tell me which term is correct?)

Monopoly Tycoon, Test Drive 6 and Ford Racing 2 all use the Windows Media Source Filter to play back .wma files from where the game is installed (no CD audio streaming).
I spent so long trying to figure out how to get the WMSF working properly and **fully**, that I just thought it was worth to point this out (if it isn't already in the core filters).

_Also_, there are two other files that are important for the correct usage of the WMSF. 
The qasf.dll must be version 6 or below (or 7, I don't remember) for the Windows Media Audio Compressor to be used by Windows. **Also also also, the qasf.dll MUST be an earlier version so that the music does not skip around in the games listed above; all are affected.** That audio compressor, which existed in Windows XP must also be existent, if it isn't already included in Windows Vista and later.

**Comment by ValeryAnisimovsky** [comment]
WMA files are natively supported in Windows, so GMFCore has nothing to do with WMA. GMFCore is about the file formats, which are not supported by the system.
